spring:
  datasource:
#    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=gd94b42ae847b9b_hanatax_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    url: jdbc:oracle:thin:@hanatax_high?TNS_ADMIN=/Users/wldnj/Downloads/Wallet_HANATAX
    username: admin
    password: Tthdsong12!!
    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#    show-sql: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:hanamapper/*.xml

logging:
  level:
    org.springframework: INFO
    org.mybatis: INFO
