name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시가 있을 때 배포

jobs:
  build:
    runs-on: ubuntu-22.04  # 백엔드를 위한 Ubuntu 환경

    steps:
      - name: Checkout source code. # GitHub Repo에서 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17 # JDK 11 설정 (스프링 부트용)
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Create zip file
        run: zip -qq -r ./build-be.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # 업데이트된 버전
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload to S3 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-southeast-2 ./build-be.zip s3://my-github-actions-s3-bucket-cicd/build-be.zip

      - name: Deploy to EC2 # EC2로 배포
        run: |
          aws deploy create-deployment \
            --application-name my-backend-codedeploy-app \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name my-backend-codedeploy-deployment-group \
            --s3-location bucket=my-github-actions-s3-bucket-cicd,key=build-be.zip,bundleType=zip
